mysql:
  username: root
  password: Mysql123456/
  host: 134.175.33.133
  port: 3306
kafka:
  host: localhost
  port: 9092
redis:
  host: localhost
  port: 6379
  password: redis9898008
elasticsearch:
  host: 101.132.150.8
  port: 9200
